//! Sun and atmosphere: the planet-scale [`Atmosphere`] entity plus the sun
//! [`DirectionalLight`] that drives sky color, the visible [`SunDisk`], and
//! aerial perspective on all PBR geometry.
//!
//! The atmosphere's lookup textures are generated by compute shaders, so the
//! sky only renders on WebGPU (native Vulkan is pinned in `main.rs`); on
//! WebGL2 the scene keeps its sun lighting but the sky stays the flat
//! [`ClearColor`].

use bevy::light::{atmosphere::ScatteringMedium, light_consts::lux, Atmosphere, SunDisk};
use bevy::prelude::*;

/// Sun elevation above the horizon, in degrees. Low enough for readable
/// shadows, high enough that the sun disk is comfortably in frame.
const SUN_ELEVATION_DEG: f32 = 35.0;
/// Sun azimuth in degrees, measured from +X around +Y.
const SUN_AZIMUTH_DEG: f32 = 125.0;

pub struct SkyPlugin;

impl Plugin for SkyPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(Startup, setup_sky);
    }
}

fn setup_sky(mut commands: Commands, mut medias: ResMut<Assets<ScatteringMedium>>) {
    // Spawned without a Transform, the Atmosphere's on_add hook centers the
    // planet one inner_radius below the origin, so the planet surface sits at
    // y = 0 — flush with the ground plane.
    let medium = medias.add(ScatteringMedium::earth(256, 256));
    commands.spawn(Atmosphere::earth(medium));

    commands.spawn((
        DirectionalLight {
            illuminance: lux::FULL_DAYLIGHT,
            // Shadow cost (dev profile, 1080p, ~10k boid casters + 99 cubes,
            // camera ~60 m up, idle machine): ~61 ms/frame with shadows vs
            // ~51.5 ms without — ~9.5 ms (~16%). Mostly GPU-bound, so the
            // delta should carry to release builds.
            shadow_maps_enabled: true,
            ..default()
        },
        SunDisk::EARTH,
        sun_transform(SUN_ELEVATION_DEG, SUN_AZIMUTH_DEG),
    ));
}

/// Places a directional light `elevation_deg` above the horizon at
/// `azimuth_deg` (from +X around +Y), looking at the origin so its forward
/// axis — the direction light travels — points down at the scene.
fn sun_transform(elevation_deg: f32, azimuth_deg: f32) -> Transform {
    let (el_sin, el_cos) = elevation_deg.to_radians().sin_cos();
    let (az_sin, az_cos) = azimuth_deg.to_radians().sin_cos();
    let dir = Vec3::new(el_cos * az_cos, el_sin, el_cos * az_sin);
    Transform::from_translation(dir * 1000.0).looking_at(Vec3::ZERO, Vec3::Y)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sun_shines_downward_from_its_position() {
        let t = sun_transform(35.0, 125.0);
        assert!(t.forward().y < 0.0);
        let expected_y = 1000.0 * 35.0f32.to_radians().sin();
        assert!((t.translation.y - expected_y).abs() < 1e-3);
    }

    #[test]
    fn horizon_sun_shines_horizontally() {
        let t = sun_transform(0.0, 0.0);
        assert!(t.forward().y.abs() < 1e-5);
    }

    #[test]
    fn higher_elevation_points_more_downward() {
        let low = sun_transform(20.0, 0.0).forward().y;
        let high = sun_transform(80.0, 0.0).forward().y;
        assert!(high < low);
    }
}
