//! Sun and atmosphere: the planet-scale [`Atmosphere`] entity plus the sun
//! [`DirectionalLight`] that drives sky color, the visible [`SunDisk`], and
//! aerial perspective on all PBR geometry.
//!
//! The atmosphere is currently opt-in from the bench (`main.rs` keeps it off
//! by default): Bevy 0.19 regenerates/refilters its environment-map cubemap
//! every frame, and the upstream on-demand fix is still open. The sun,
//! shadows, flat ambient fallback, and [`ClearColor`] sky remain on.
//!
//! The atmosphere's lookup textures are generated by compute shaders, so the
//! sky only renders on WebGPU (native Vulkan is pinned in `main.rs`); on
//! WebGL2 the scene keeps its sun lighting but the sky stays the flat
//! [`ClearColor`].

use bevy::light::{Atmosphere, SunDisk, atmosphere::ScatteringMedium, light_consts::lux};
use bevy::prelude::*;

/// Sun elevation above the horizon, in degrees. Low enough for readable
/// shadows, high enough that the sun disk is comfortably in frame.
const SUN_ELEVATION_DEG: f32 = 35.0;
/// Sun azimuth in degrees, measured from +X around +Y.
const SUN_AZIMUTH_DEG: f32 = 125.0;

/// Runtime-tunable sky parameters; exposed as sliders by the debug UI.
/// Defaults mirror the consts above.
#[derive(Resource, Debug, Clone, Copy)]
pub struct SkyTuning {
    /// Sun elevation above the horizon, degrees.
    pub sun_elevation_deg: f32,
    /// Sun azimuth from +X around +Y, degrees.
    pub sun_azimuth_deg: f32,
    /// Directional light shadow maps (see the cost note on `setup_sky`).
    pub shadows: bool,
}

impl Default for SkyTuning {
    fn default() -> Self {
        Self {
            sun_elevation_deg: SUN_ELEVATION_DEG,
            sun_azimuth_deg: SUN_AZIMUTH_DEG,
            shadows: true,
        }
    }
}

/// Resolution of the per-frame sky environment cubemap that drives ambient
/// light and reflections while the atmosphere's env-map probe is enabled.
/// Matches upstream's lowered default (bevyengine/bevy#24738); Bevy 0.19.1
/// itself still ships 512 px.
pub const ENVIRONMENT_MAP_SIZE_PX: UVec2 = UVec2::splat(128);

pub struct SkyPlugin;

impl Plugin for SkyPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<SkyTuning>()
            .add_systems(Startup, setup_sky)
            .add_systems(Update, update_sun.run_if(resource_changed::<SkyTuning>));
    }
}

fn setup_sky(
    mut commands: Commands,
    mut medias: ResMut<Assets<ScatteringMedium>>,
    tuning: Res<SkyTuning>,
) {
    // Spawned without a Transform, the Atmosphere's on_add hook centers the
    // planet one inner_radius below the origin, so the planet surface sits at
    // y = 0 — flush with the ground plane.
    let medium = medias.add(ScatteringMedium::earth(256, 256));
    commands.spawn(Atmosphere::earth(medium));

    commands.spawn((
        DirectionalLight {
            illuminance: lux::FULL_DAYLIGHT,
            // Shadow cost (dev profile, 1080p, ~10k boid casters + 99 cubes,
            // camera ~60 m up, idle machine): ~61 ms/frame with shadows vs
            // ~51.5 ms without — ~9.5 ms (~16%). Mostly GPU-bound, so the
            // delta should carry to release builds.
            shadow_maps_enabled: tuning.shadows,
            ..default()
        },
        SunDisk::EARTH,
        sun_transform(tuning.sun_elevation_deg, tuning.sun_azimuth_deg),
    ));
}

/// Applies [`SkyTuning`] to the sun light. Runs only when the tuning
/// actually changed (debug sliders), not every frame.
fn update_sun(
    mut sun: Query<(&mut Transform, &mut DirectionalLight), With<SunDisk>>,
    tuning: Res<SkyTuning>,
) {
    for (mut transform, mut light) in &mut sun {
        *transform = sun_transform(tuning.sun_elevation_deg, tuning.sun_azimuth_deg);
        light.shadow_maps_enabled = tuning.shadows;
    }
}

/// Places a directional light `elevation_deg` above the horizon at
/// `azimuth_deg` (from +X around +Y), looking at the origin so its forward
/// axis — the direction light travels — points down at the scene.
fn sun_transform(elevation_deg: f32, azimuth_deg: f32) -> Transform {
    let (el_sin, el_cos) = elevation_deg.to_radians().sin_cos();
    let (az_sin, az_cos) = azimuth_deg.to_radians().sin_cos();
    let dir = Vec3::new(el_cos * az_cos, el_sin, el_cos * az_sin);
    Transform::from_translation(dir * 1000.0).looking_at(Vec3::ZERO, Vec3::Y)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sun_shines_downward_from_its_position() {
        let t = sun_transform(35.0, 125.0);
        assert!(t.forward().y < 0.0);
        let expected_y = 1000.0 * 35.0f32.to_radians().sin();
        assert!((t.translation.y - expected_y).abs() < 1e-3);
    }

    #[test]
    fn horizon_sun_shines_horizontally() {
        let t = sun_transform(0.0, 0.0);
        assert!(t.forward().y.abs() < 1e-5);
    }

    #[test]
    fn higher_elevation_points_more_downward() {
        let low = sun_transform(20.0, 0.0).forward().y;
        let high = sun_transform(80.0, 0.0).forward().y;
        assert!(high < low);
    }
}
